[package]
name = "wasm-sleep"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "wasm_sleep"
#crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
js-sys = "*"
fluvio-wasm-timer = "*"
